### ISSUE TITLE
Android studio failed to resolve the dependency

### ISSUE THREAD

**Issue by jordan-jakisa** [abdullahalhakimi/SmoothMotion#12]
I followed the steps in the ReadMe and I also used my Brain to think 😅 and added the dependency for the app in my build.gradle file but the dependency is not being resolved!

![image](https://github.com/user-attachments/assets/37c23b47-0113-4c6e-86e8-9060d744fd76)

**Comment by abdullahalhakimi** [comment]
There was issue with the publishing, just Follow these steps and it will work. 

## Installation
Add the JitPack repository to your settings.gradle.kts

```gradle
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
    }
}
```


###  Add the dependency to your build.gradle.kts
```gradle
dependencies {
    implementation ("com.github.abdullahalhakimi:SmoothMotion:1.0.1")
}
```

let me know if you had any other  issue 😁 @jordan-jakisa


![2024-10-07-185033_hyprshot](https://github.com/user-attachments/assets/480a1665-b876-46d9-a0bf-40f86fc01d41)

**Comment by jordan-jakisa** [comment]
This still didn't work!

**Comment by abdullahalhakimi** [comment]
I already test it in different projects, can you share a screenshot
